services:
  db:
    image: postgres:15-alpine
    container_name: adminex_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adminex_docker_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: adminex_app
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/adminex_docker_dev
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true # docker run -t

  proxy-inverso:
    image: nginx:alpine
    container_name: adminex_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - app

volumes:
  postgres_data:
